language: objective-c
osx_image: xcode7.2
xcode_project: NetworkKit.xcodeproj
xcode_scheme: NetworkKitTests

script:
- xcodebuild clean build test -project NetworkKit.xcodeproj -scheme NetworkKitTests
